[package]
name = "host-io"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
arbutil = { path = "../../arbutil/", features = ["wavm"] }
go-abi = { path = "../go-abi" }
