[package]
name = "jit"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmer = "2.3.0"
eyre = "0.6.5"
parking_lot = "0.12.1"
rand = { version = "0.8.4", default-features = false }
rand_pcg = { version = "0.3.1", default-features = false }
