[package]
name = "wavmconvert"
version = "0.1.0"
authors = ["Offchain Labs"]
edition = "2021"
homepage = "https://arbitrum.io"
license = "BSL"
repository = "https://github.com/OffchainLabs/nitro.git"
rust-version = "1.67"


[dependencies]
arbutil = { path = "../../arbutil" }
prover = { path = "../../prover" }
wasmer = { path = "../../tools/wasmer/lib/api" }
