[package]
name = "user-host"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
arbutil = { path = "../../arbutil/", features = ["wavm"] }
hashbrown = "0.12.3"
hex = "0.4.3"
