[package]
name = "user-host"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
arbutil = { path = "../../arbutil/", features = ["wavm"] }
prover = { path = "../../prover/", default-features = false }
go-abi = { path = "../go-abi" }
hex = "0.4.3"
