[package]
name = "wasi-stub"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
paste = {versoion="1.0.14"}
callerenv = { path = "../../callerenv/", features = ["static_caller"] }
wee_alloc = "0.4.5"

