name: CI

on:
  pull_request:
    paths-ignore:
      - 'arbitrator/**'
      - 'solgen/src/osp/**'
      - 'solgen/src/mock/**'
      - 'solgen/test/**'
      - 'solgen/hardhat.config.ts'

jobs:
  rustfmt:
    name: Rust formatting check
    runs-on: ubuntu-latest
  coverage:
    name: Run Arbitrator tests
    runs-on: ubuntu-latest
