name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: ArbOS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_CHECKOUT }}
          submodules: recursive

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gotestsum

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      - name: Format check
        run: |
          gofmt -l arbos
          test -z "$(gofmt -l arbos)"

      - name: Build and Test
        run: make -j
