name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_CHECKOUT }}
          submodules: recursive

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_CHECKOUT }}
          submodules: recursive

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gotestsum

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Build and Test
        run: make -j
