name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: ArbOS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_CHECKOUT }}
          submodules: recursive

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gotestsum

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Generate precompiles
        run: make -j

      - name: Build
        run: go build -v ./arbos/...

      - name: Test ArbOS
        run: cd arbos && gotestsum --format short-verbose

      - name: Test ArbState
        run: cd arbstate && gotestsum --format short-verbose
