name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings

jobs:
  rustfmt:
    name: Rust formatting check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Ubuntu dependencies
        run: |
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update && sudo apt-get install -y \
            build-essential cmake nodejs ethereum

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install rust nightly
        run: |
          rustup toolchain install nightly
          rustup target add --toolchain nightly wasm32-unknown-unknown

      - name: Install latest wabt
        run: |
          cd "$(mktemp -d)"
          git clone --recursive -b 1.0.24 https://github.com/WebAssembly/wabt .
          mkdir build
          cd build
          cmake ..
          make -j
          sudo make install

      - name: Run rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: Make proofs from test cases
        run: make -j

      - name: Start geth server
        run: |
          geth --dev --http --http.port 8545 &
          sleep 2

      - name: Run proof validation tests
        run: |
          npm install --global yarn
          cd rollup
          yarn install
          yarn hardhat test --network localhost
