name: Release CI
run-name: Release CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
  pull_request:
    types:
      - master
      - develop

jobs:
  build_and_run:
    runs-on: ubuntu-8

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Check PR Label For Release label
      run: |
        if contains(github.event.pull_request.labels.*.name, 'release') 
          echo "Release candidate."
        else
          echo "Not a release candidate. Skipping workflow."
          exit 0
        fi

    - name: Build nitro-fuzzer Docker Image
      run: docker build --target nitro-fuzzer -t nitro-fuzzer .

    - name: Run Docker Container
      run: docker run nitro-fuzzer
